# https://www.guyrutenberg.com/2014/05/02/make-offline-mirror-of-a-site-using-wget/
site:
	wget --mirror --convert-links --adjust-extension --page-requisites  --no-parent https://buddhadust.net/dhamma-vinaya/pts_pali/
