# https://www.guyrutenberg.com/2014/05/02/make-offline-mirror-of-a-site-using-wget/
site:
	wget --mirror --convert-links --adjust-extension --page-requisites  --no-parent https://buddhadust.net/dhamma-vinaya/pts_pali/

site2:
	wget --convert-links http://gretil.sub.uni-goettingen.de/gretil.html

site3:
	wget --convert-links https://www.thepathofpurity.com/home/%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B9%84%E0%B8%95%E0%B8%A3%E0%B8%9B-%E0%B8%8E%E0%B8%81-pdf/%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B9%84%E0%B8%95%E0%B8%A3%E0%B8%9B-%E0%B8%8E%E0%B8%81%E0%B8%9A%E0%B8%B2%E0%B8%A5-%E0%B8%AA%E0%B8%A2%E0%B8%B2%E0%B8%A1%E0%B8%A3-%E0%B8%90/
	wget --no-directories --content-disposition -e robots=off -A.pdf -r -l 1 https://www.thepathofpurity.com/home/%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B9%84%E0%B8%95%E0%B8%A3%E0%B8%9B-%E0%B8%8E%E0%B8%81-pdf/%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B9%84%E0%B8%95%E0%B8%A3%E0%B8%9B-%E0%B8%8E%E0%B8%81%E0%B8%9A%E0%B8%B2%E0%B8%A5-%E0%B8%AA%E0%B8%A2%E0%B8%B2%E0%B8%A1%E0%B8%A3-%E0%B8%90/

site4:
	wget --convert-links https://www.thepathofpurity.com/home/%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B9%84%E0%B8%95%E0%B8%A3%E0%B8%9B-%E0%B8%8E%E0%B8%81-pdf/%E0%B8%AD%E0%B8%A3%E0%B8%A3%E0%B8%96%E0%B8%81%E0%B8%96%E0%B8%B2%E0%B8%9A%E0%B8%B2%E0%B8%A5-%E0%B8%AA%E0%B8%A2%E0%B8%B2%E0%B8%A1%E0%B8%A3-%E0%B8%90/
